server:
  port: 8086

spring:
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: dubbo-provider
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://localhost:2181